import * as THREE from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
gsap.registerPlugin(ScrollTrigger);ScrollTrigger.config({ignoreMobileResize:true});
const $=s=>document.querySelector(s);let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{const saved=sessionStorage.getItem('ora-motion');if(saved!==null)reduced=saved==='reduced';}catch{}
document.body.classList.toggle('reduced',reduced);$('#motion-toggle').textContent=reduced?'Enable motion':'Reduce motion';$('#motion-toggle').setAttribute('aria-pressed',String(reduced));
const lenis=new Lenis({duration:1.05,smoothWheel:!reduced});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0);
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=$(a.getAttribute('href'));if(target){e.preventDefault();lenis.scrollTo(target,{duration:reduced?0:1.3});}}));
const reveal=$('.word-reveal'),words=reveal.textContent.trim().split(' ');reveal.replaceChildren();for(const word of words){const span=document.createElement('span');span.className='word';span.textContent=word;reveal.append(span,document.createTextNode(' '));}
const compactQuery=matchMedia('(max-height:600px)');const stacked=()=>innerWidth<=1024&&innerHeight>600;document.body.classList.toggle('compact',compactQuery.matches);
const motion={p:0};let animationContext;
function setMotion(){animationContext?.revert();$('.ritual-title').style.color='';if(reduced||compactQuery.matches)return;
animationContext=gsap.context(()=>{
const hero=gsap.timeline({scrollTrigger:{trigger:'.opening',start:'top top',end:'bottom bottom',scrub:.7}});
hero.to(motion,{p:1,duration:1,ease:'none'},0).to('.title-night',{xPercent:-95,yPercent:-35,rotation:-8,opacity:0,duration:.24,ease:'power2.in'},.05).to('.title-shift',{xPercent:95,yPercent:45,rotation:8,opacity:0,duration:.24,ease:'power2.in'},.05).to('.hero-eyebrow',{y:-50,opacity:0,duration:.13},.03).to('.hero-bottom,.hero-side',{y:60,opacity:0,duration:.15},.05).to('.orbit-one',{scale:2.8,rotation:110,opacity:0,duration:.5},.1).to('.orbit-two',{scale:2,rotation:-60,opacity:0,duration:.5},.1).fromTo('.opening-next',{autoAlpha:0,y:100},{autoAlpha:1,y:0,duration:.18},.27).to('.opening-next',{y:-130,autoAlpha:0,duration:.17},.59).fromTo('.opening-final',{autoAlpha:0,scale:.6,y:100},{autoAlpha:1,scale:1,y:0,duration:.2},.73).to('.ambient',{scale:2,opacity:.3,duration:.5},.4);
gsap.timeline({scrollTrigger:{trigger:'.campaign',start:'top top',end:'bottom bottom',scrub:.6}}).to('.campaign-intro',{yPercent:-65,scale:.8,opacity:0,duration:.35},.04).to('.campaign-window',{top:'0%',left:'0%',right:'0%',bottom:'0%',borderRadius:'0px',duration:.55,ease:'power2.inOut'},.06).to('.campaign-window img',{scale:1,duration:.7},.1).fromTo('.campaign-caption',{autoAlpha:0,y:90},{autoAlpha:1,y:0,duration:.25},.58).to({}, {duration:.17});
const formula=gsap.timeline({scrollTrigger:{trigger:'.formula',start:'top top',end:'bottom bottom',scrub:.65}});formula.from('.formula-heading',{y:80,opacity:0,duration:.15},0);
if(stacked()){formula.from('.card-one',{yPercent:110,rotation:12,opacity:0,duration:.18},.04).from('.card-two',{yPercent:130,rotation:-12,opacity:0,duration:.2},.26).to('.card-one',{scale:.9,rotation:-5,y:-15,duration:.2},.26).from('.card-three',{yPercent:130,rotation:12,opacity:0,duration:.2},.49).to('.card-two',{scale:.93,rotation:5,y:-8,duration:.2},.49);}else{formula.from('.card-one',{xPercent:-130,y:180,rotation:-22,opacity:0,duration:.28},.03).from('.card-two',{yPercent:130,rotationX:40,opacity:0,duration:.28},.15).from('.card-three',{xPercent:130,y:180,rotation:22,opacity:0,duration:.28},.27);}
formula.to('.formula-heading',{y:-120,opacity:0,duration:.18},.74).to('.ingredient-card',{yPercent:-160,rotation:-10,opacity:0,stagger:.035,duration:.17},.75).fromTo('.formula-signoff',{autoAlpha:0,scale:.8},{autoAlpha:1,scale:1,duration:.16},.94);
gsap.timeline({scrollTrigger:{trigger:'.manifesto',start:'top top',end:'bottom bottom',scrub:.5}}).from('.manifesto-stage>.eyebrow',{x:-60,opacity:0,duration:.1}).to('.word-reveal .word',{color:'#ffffff',stagger:.06,duration:.12},.05).from('.manifesto-bottom',{y:40,opacity:0,duration:.18},.8);
gsap.to('.ritual-track',{x:()=>-document.querySelector(".ritual-stage").clientWidth*2,ease:'none',scrollTrigger:{trigger:'.ritual',start:'top top',end:'bottom bottom',scrub:.6,invalidateOnRefresh:true,onUpdate:s=>{$('.ritual-counter').textContent=`0${Math.min(3,Math.floor(s.progress*3)+1)} — 03`;$('.ritual-line span').style.width=`${s.progress*100}%`;$('.ritual-title').style.color=s.progress>.8?'#e6e9f0':'#080c23';}}});
gsap.timeline({scrollTrigger:{trigger:'.shop',start:'top bottom',end:'top top',scrub:.6}}).from('.shop-heading',{x:-150,opacity:0,duration:1},0).from('.shop-image',{scale:.65,rotation:-8,opacity:.2,duration:1},0).from('.shop-info',{x:150,y:65,opacity:0,duration:1},.1);
gsap.to('.shop-image img',{scale:1.05,scrollTrigger:{trigger:'.shop',start:'top top',end:'bottom bottom',scrub:.5}});gsap.from('.footer-statement',{y:100,rotation:3,opacity:.15,scrollTrigger:{trigger:'footer',start:'top bottom',end:'top 15%',scrub:.6}});
});}
setMotion();ScrollTrigger.create({start:0,end:'max',onUpdate:s=>$('.page-progress').style.width=`${s.progress*100}%`});document.querySelectorAll('.chapter-nav a').forEach(a=>ScrollTrigger.create({trigger:a.getAttribute('href'),start:'top center',end:'bottom center',onToggle:s=>a.classList.toggle('active',s.isActive)}));
let renderer,scene,camera,jar,lid;
function makeLabel(){const c=document.createElement('canvas');c.width=1536;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#f0eee5';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#09132d';ctx.textAlign='center';ctx.font='128px Georgia';ctx.fillText('ora',768,165);ctx.font='34px Arial';ctx.fillText('M I D N I G H T   R E S E T',768,275);ctx.font='22px Arial';ctx.fillText('NOURISHING NIGHT CREAM',768,342);ctx.font='18px Arial';ctx.fillText('50 mL / 1.7 fl. oz.',768,427);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return tex;}
try{const el=$('#jar-scene');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,.15,10);renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;el.append(renderer.domElement);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.05).texture;pmrem.dispose();scene.add(new THREE.HemisphereLight(0xc7d7ff,0x040719,2));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(-4,5,6);scene.add(key);const rim=new THREE.DirectionalLight(0x5577ff,6);rim.position.set(4,2,-3);scene.add(rim);jar=new THREE.Group();scene.add(jar);const blue=new THREE.MeshPhysicalMaterial({color:0x071752,metalness:.45,roughness:.17,clearcoat:1,clearcoatRoughness:.1});const profile=[new THREE.Vector2(0,-.65),new THREE.Vector2(.99,-.65),new THREE.Vector2(1.11,-.61),new THREE.Vector2(1.17,-.5),new THREE.Vector2(1.17,.46),new THREE.Vector2(1.1,.58),new THREE.Vector2(.98,.59)];jar.add(new THREE.Mesh(new THREE.LatheGeometry(profile,100),blue));const silver=new THREE.MeshStandardMaterial({color:0xc3ccd9,metalness:1,roughness:.24});lid=new THREE.Group();jar.add(lid);const cap=new THREE.Mesh(new THREE.CylinderGeometry(1.16,1.18,.24,96),silver);cap.position.y=.74;lid.add(cap);const top=new THREE.Mesh(new THREE.CylinderGeometry(1.09,1.15,.06,96),silver);top.position.y=.885;lid.add(top);const edge=new THREE.Mesh(new THREE.TorusGeometry(1.15,.035,12,96),silver);edge.rotation.x=Math.PI/2;edge.position.y=.63;lid.add(edge);const cream=new THREE.Mesh(new THREE.CylinderGeometry(.96,.96,.08,80),new THREE.MeshStandardMaterial({color:0xf0e8d5,roughness:.7}));cream.position.y=.52;jar.add(cream);const wrap=new THREE.Mesh(new THREE.CylinderGeometry(1.179,1.179,.79,80,1,true,-.92,1.84),new THREE.MeshBasicMaterial({map:makeLabel(),side:THREE.DoubleSide}));wrap.position.y=-.01;jar.add(wrap);const base=new THREE.Mesh(new THREE.TorusGeometry(1.08,.065,16,100),blue);base.rotation.x=Math.PI/2;base.position.y=-.59;jar.add(base);function size(){renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(size).observe(el);size();}catch(e){$('#jar-scene').innerHTML='<img src="assets/midnight-campaign.png" alt="ORA Midnight Reset cream jar" style="position:absolute;width:45%;height:40%;object-fit:cover;left:30%;top:35%">';console.warn('Using product image fallback',e);}
let time=0;const clock=new THREE.Clock(),visible={hero:true};new IntersectionObserver(entries=>visible.hero=entries[0].isIntersecting).observe($('.opening'));function render(){requestAnimationFrame(render);const dt=Math.min(clock.getDelta(),.04);if(!reduced)time+=dt;if(!renderer||!visible.hero||document.hidden)return;const p=reduced?0:motion.p,m=stacked()||innerWidth<761,middle=THREE.MathUtils.smoothstep(p,.14,.37),exit=THREE.MathUtils.smoothstep(p,.64,.87);jar.position.set((m?.08:0)+(m?.45:2.15)*middle,(m?-1.0:-.35)-(m?.58:0)*middle-3.8*exit,0);if(!reduced)jar.position.y+=Math.sin(time*.8)*.07;jar.scale.setScalar((m?.73:1.08)*(1-.13*middle));jar.rotation.set(.15+(reduced?0:Math.sin(time*.45)*.07+middle*.2),reduced?0:Math.sin(time*.4)*.16+p*Math.PI*2,-.13+(reduced?0:Math.sin(p*Math.PI)*.25));lid.position.y=reduced?0:THREE.MathUtils.smoothstep(p,.27,.5)*.85;lid.rotation.y=p*1.5;lid.rotation.z=middle*.12;renderer.render(scene,camera);}render();
$('#motion-toggle').onclick=()=>{try{sessionStorage.setItem('ora-motion',reduced?'full':'reduced');}catch{}reduced=!reduced;document.body.classList.toggle('reduced',reduced);$('#motion-toggle').textContent=reduced?'Enable motion':'Reduce motion';$('#motion-toggle').setAttribute('aria-pressed',String(reduced));lenis.options.smoothWheel=!reduced;setMotion();ScrollTrigger.refresh();};
let qty=0;const bag=$('#bag');function drawBag(){$('#bag-count').textContent=qty;$('.bag-content').innerHTML=qty?`<h3>The Midnight Reset</h3><p>Nourishing night cream · 50 mL</p><div class="bag-actions"><button data-qty="-1" aria-label="Remove one jar">−</button><span>${qty}</span><button data-qty="1" aria-label="Add one jar">+</button></div><p>Subtotal · $${qty*68}</p>`:'<p>Your bag is taking a moment.<br>Find your new evening essential below.</p>';document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{qty=Math.max(0,qty+Number(b.dataset.qty));drawBag();});}
$('.add-button').onclick=()=>{qty++;drawBag();$('#toast').textContent='The Midnight Reset — added to your bag';gsap.killTweensOf('#toast');gsap.timeline().to('#toast',{opacity:1,duration:.2}).to('#toast',{opacity:0,duration:.3,delay:2});};$('.bag-open').onclick=()=>{drawBag();bag.showModal();lenis.stop();};$('.close-bag').onclick=$('.continue-button').onclick=()=>bag.close();bag.addEventListener('close',()=>lenis.start());bag.addEventListener('wheel',e=>e.stopPropagation());
let lastWidth=innerWidth,lastCompact=compactQuery.matches;window.addEventListener('resize',()=>{clearTimeout(window.oraResizeTimer);window.oraResizeTimer=setTimeout(()=>{if(lastWidth===innerWidth&&lastCompact===compactQuery.matches)return;document.body.classList.toggle("compact",compactQuery.matches);lastWidth=innerWidth;lastCompact=compactQuery.matches;setMotion();ScrollTrigger.refresh();},180);});window.addEventListener('load',()=>ScrollTrigger.refresh());document.fonts.ready.then(()=>ScrollTrigger.refresh());
